export * from "./auth-schema"
export * from "./clasesSchemas"
export * from "./groupSchema"
export * from './horariosSchema'
export * from "./parentsSchema"
export * from "./studentsSchema"
export * from "./subjectsSchema"
export * from "./tasks-schema"
export * from "./teachersSchema"