export * from "./anuncios-schema"
export * from "./attendance-schema"
export * from "./auth-schema"
export * from "./clasesSchemas"
export * from "./examen-schema"
export * from "./groupSchema"
export * from './horariosSchema'
export * from './notifications-schema'
export * from "./parentsSchema"
export * from "./studentsSchema"
export * from "./subjectsSchema"
export * from "./tasks-schema"
export * from "./taskAttachments-schema"
export * from "./teachersSchema"